### ISSUE TITLE
[enchantjs] ジャンプ機能の実装

### ISSUE THREAD

**Issue by eeic19** [turenar/mayfes2018-pikyou#108]
表題通り、落とし穴などを回避できるジャンプ機能の実装です。

仕様としては、

- 基本的に1方向へ距離2の移動を行う(1マス飛び越える)
- 1マス先が壁(に準ずるもの)の場合、そもそもジャンプが行われない
- 2マス先が壁の場合、移動は1マスのみになる(通常のmoveとほぼ同じ)
- 飛び越えた1マスの効果は受けず、そのマスへの干渉も行えない

の予定です。

**Comment by eeic19** [comment]
仕様は

- 次の移動(すすむ)を”ジャンプ移動”にする

とか

- そのターンだけ自身をジャンプ状態にする

とかの方が良いかも？

**Comment by aqla114** [comment]
実装できたっぽいので閉じます。
