### ISSUE TITLE
[blockly] blockly用のxmlがhtmlファイル内に直接記述されている。

### ISSUE THREAD

**Issue by aqla114** [turenar/mayfes2018-pikyou#12]
xmlファイルを作ってhtmlから読み出すようにする。

**Comment by turenar** [comment]
初めの方のステージとかで、必要のないblocklyのコマンドを隠せるような拡張ができるとなお良い (必須ではない)

**Comment by aqla114** [comment]
必要のないblockを隠す実装、色々とやり方がありそうで割と大きめのタスクっぽいので別にissue立てます。

**Comment by aqla114** [comment]
mergeされたので閉じます。
