### ISSUE TITLE
[enchantjs/blockly] 現在の総コストが表示されるようにする 

### ISSUE THREAD

**Issue by aqla114** [turenar/mayfes2018-pikyou#127]
表題の通り。組みながら総コストがわかるようにする。

**Comment by aqla114** [comment]
ブロックのコストは、好きなタイミングで、ScoreManagerクラスのStaticメソッドgetBlockCostSumを呼ぶと得られる。

**Comment by azoson** [comment]
これやろうと思ってるんじゃが、どこに総コスト表示したいんや？

**Comment by aqla114** [comment]
どこに表示するのが一番わかりやすいんですかねぇ...
マップの右下（ここでいうマップの右下はマップ内の右下ではなく、マップ外部かつマップの右下、すなわちスタートボタンの左上を意味しています）とかが無難そうですけど、ぶっちゃけ分かりません。

**Comment by azoson** [comment]
気持ち的には blockly editor の辺りに出ていて欲しい気がするにゃもけど、blockly editor とかいうのあんまいじりたくない。面倒くさそうなので。まあいくつか考えるわ。

**Comment by azoson** [comment]
多分「ここから下にブロックを繋げてにゃも」のブロックのメッセージにコスト表示されとればええやろみたいな気持ちになった

**Comment by aqla114** [comment]
メェァージされたので閉じます。
