### ISSUE TITLE
[blockly] 実行ブロックを削除できてしまう

### ISSUE THREAD

**Issue by eeic19** [turenar/mayfes2018-pikyou#130]
executeブロックもブロック全削除(右クリックから使える)の対象となっているので、これを消えないようにする。

**Comment by eeic19** [comment]
現在PlayingSceneに移行するとexecuteブロックが削除できるようになっているので、修正を行う。

**Comment by turenar** [comment]
probably regression in #143

**Comment by aqla114** [comment]
#143 の実装ミスって感じで完全にごめんなさい。

**Comment by aqla114** [comment]
多分大丈夫です。
