### ISSUE TITLE
[blockly/enchantjs] タイマー機能

### ISSUE THREAD

**Issue by aqla114** [turenar/mayfes2018-pikyou#135]
プレイ時間が一定時間を超えたら、キリのいいところで「次の人に変わってね！」が表示されるようにする。

**Comment by aqla114** [comment]
ここの「キリのいいところ」はScene遷移時が妥当そう。

**Comment by turenar** [comment]
次の人に変わる条件は次の人がいることを前提にしたいけど、どうしよう……サーバー使う？

**Comment by aqla114** [comment]
サーバあまり使いたくないですけど、 #139 の件もありますし必要ですかね...

**Comment by turenar** [comment]
#139 はサーバーに保存する意味薄いと思うんだけど、こっちをつけるならサーバーはたぶん必要よね……

**Comment by turenar** [comment]
初回アクセス時 (Cookie/LocalStorageにアクセスキーが存在しない？) ときに、席番号を打たせる。

{"seat_number":number}で/timekeeper/api/attendにアクセス、返ってきたcomputer_hashを保存。

X秒ごとに/timekeeper/api/ping/(hash)にアクセス。stateが1でscene変更時に、2で強制退席。
