### ISSUE TITLE
ステージのクリア状況をどこかに保存する

### ISSUE THREAD

**Issue by turenar** [turenar/mayfes2018-pikyou#139]

**Comment by aqla114** [comment]
かなりissueの名前が漠然としてるんですけど、これはキャッシュとかに残すというお気持ちでよろし？

**Comment by turenar** [comment]
CookieかLocalStorageが妥当かと、キャッシュは残しようがないような……

サーバーに残してもいい

**Comment by aqla114** [comment]
いや、単純に僕がweb上のデータの残し方に詳しくないのでキャッシュぐらいしか知らなかったんです...
サーバめんどくさいしLocalStorageが妥当かなぁという気もしますね。

**Comment by turenar** [comment]
https://developer.mozilla.org/ja/docs/Web/API/Window/localStorage

> 注: iOS 5.1 からは、Safari Mobile は localStorage データをキャッシュフォルダーに保存し、そこは時々 OS の指示で (よくあるのはスペースが少ない場合) 掃除されがちです。

らしいので、Cookieに残しておいたほうが良いかもしれないっすね……iPadで普通にプレイしてたら突然データが消えたは辛いので……

**Comment by aqla114** [comment]
そもそもiPadとかで今のピ教遊べるんですかね？

**Comment by turenar** [comment]
タブレット持ってないからわからないけど、enchantは少なくともクリックではなくタップ環境のこととか考えられているっぽい、まあ対象 (推奨) 環境にはしないつもりなのでどっちでも良い

**Comment by aqla114** [comment]
LocalStrageでいい気がしますねぇ...
