### ISSUE TITLE
[enchantjs] 落とし穴の判定がNotをつけると正しく行われない

### ISSUE THREAD

**Issue by eeic19** [turenar/mayfes2018-pikyou#146]
!front === 8
となるため。
check_obstacleのcodeに()をつければ解決しそう？

**Comment by eeic19** [comment]
小さいので #145 で同時に処理します。

**Comment by turenar** [comment]
https://developers.google.com/blockly/guides/create-custom-blocks/operator-precedence

@eeic19 別PRでやってください

**Comment by eeic19** [comment]
他(マーカーなど)にも同様の現象を確認しましたのでまとめて修正します。

**Comment by aqla114** [comment]
mergeしたので閉じます。
