### ISSUE TITLE
[Blockly/enchantjs] コードの実行に eval を使用している。

### ISSUE THREAD

**Issue by aqla114** [turenar/mayfes2018-pikyou#24]
Blocklyで生成したコードは文字列で得られるためこれを実行する必要がある。現在は、`eval(code);`として実行しているが、`eval`は任意のコードが実行できたり、遅かったりとあまりよろしくない（？）らしい。
もし代替手段があればそちらに切り替えたい。

**Comment by turenar** [comment]
evalは遅いけど、blocklyのツリーをinterpretするよりは早そうな気がする (要出典)
セキュリティ的にもあまり嬉しくないけど、やばいコードを書かせないようにさえすればいいので、そんなに重要度が高いわけではない気もする。

が、evalはやはり心理的に避けたいので、interpretできるならそちらが良いと僕も思います

**Comment by turenar** [comment]
メモ node_modules/node-blockly/blockly/core/generator.js:L91

```javascript:node_modules/node-blockly/blockly/core/generator.js
Blockly.Generator.prototype.workspaceToCode = function(workspace) {
  // (snip)
  this.init(workspace);
  var blocks = workspace.getTopBlocks(true);
  for (var x = 0, block; block = blocks[x]; x++) {
    var line = this.blockToCode(block);
    if (goog.isArray(line)) {
      // Value blocks return tuples of code and operator order.
      // Top-level blocks don't care about operator order.
      line = line[0];
    }
    if (line) {
      if (block.outputConnection && this.scrubNakedValue) {
        // This block is a naked value.  Ask the language's code generator if
        // it wants to append a semicolon, or something.
        line = this.scrubNakedValue(line);
      }
      code.push(line);
    }
  }
  code = code.join('\n');  // Blank line between each section.
  code = this.finish(code);
  // (snip)
  return code;
```

**Comment by aqla114** [comment]
まあ、確かに今回は僕らの書いたコードに関して`eval`するだけだしセキュリティ的にはそんなに問題もないですかね。速さも、たかだか30fpsに間に合えばいいので...

**Comment by turenar** [comment]
フレーム単位でevalすると、今回の要件である、「マスを移動する」の実装がめんどくさくならないかが個人的には心配かも

**Comment by aqla114** [comment]
そうですね ...ここら辺どうしようかなあという感じです。
マス目移動とは言いつつも、間の移動描画は補完する必要があると思いますしちょっとまたここら辺の実装考える必要ありそうですかね。
たぶん、 #15 がもろこの話題ですね。

**Comment by turenar** [comment]
一応、JSのsandbox化は出来るみたい

https://developers.google.com/blockly/guides/app-integration/running-javascript#run_the_interpreter

間の移動描画は……enchant.Timeline使えばできそうだけど……うーん

**Comment by aqla114** [comment]
これ、ぶっちゃけもう修正しないと思うんで閉じます。
