### ISSUE TITLE
[enchantjs] アニメーション機能を作る

### ISSUE THREAD

**Issue by aqla114** [turenar/mayfes2018-pikyou#47]
キャラクター等のアニメーションの機能を作り、sceneにisAnimation等を持たせる。

**Comment by tkygtr6** [comment]
@aqla114 @turenar 
自分でassignしておいてあれですが、もう少し詳しく説明してもらってもよろしいでしょうか。もしかして、動くとキャラの絵が変わったり向きが変わったりするやつの実装、ということですか？？

素材の問題は残っていますね、今のchara1.pngは左右移動しかサポートしていない感じはありますが、、、

**Comment by aqla114** [comment]
僕がissue立てておいてあれなんですけど、ちょっと要件が固まってない感がありますね…
slackのほうで少し話し合ってアニメーション周りどうするか固めたみがあります。

**Comment by aqla114** [comment]
今、StageSelectingやってくれてますし、僕がこれ巻き取りましょうか？

**Comment by tkygtr6** [comment]
そうですね、お願いします！

**Comment by aqla114** [comment]
必要に応じてまた開きますが、一旦閉じます。
