### ISSUE TITLE
[enchantjs] 最大ターン数を超えた時にゲームオーバーにする。

### ISSUE THREAD

**Issue by aqla114** [turenar/mayfes2018-pikyou#60]
GaomeOverになったらGameOverSceneに遷移するようにする。
GameOverの定義は仕様書参照。

**Comment by aqla114** [comment]
とりあえず落とし穴で死ぬのは実装した。
ループ行動をした際にGameOverにするかは未定なのでissueは閉じないようにしておきます。

**Comment by aqla114** [comment]
最大ターン数を定義して、そのターンを超えた場合はゲームオーバー扱いにしたい。

**Comment by aqla114** [comment]
最大ターン（移動）数は50、合わせて残り移動数も表示されると嬉しい。

**Comment by turenar** [comment]
最大ターンが決まってるなら、一つ一つのブロックの実行時間が長い (1sec？) ほうがいいかも……

すごい勢いで残りターン数が減っていくのはちょっとなあという気分がある
