### ISSUE TITLE
[enchantjs]goalに到達しても反映されないことがある。

### ISSUE THREAD

**Issue by eeic19** [turenar/mayfes2018-pikyou#68]
遠回りをしてgoalに到達するとgoalの判定が正しく行われない。

**Comment by eeic19** [comment]
(訂正)検証の結果遠回りは関係なしでした。

**Comment by aqla114** [comment]
これ、goal判定のifの中身がダメなせい。
this.getFeetTile() === MapChip.Goalの時、moveFowardが実行されないようにすれば多分解決する。

**Comment by aqla114** [comment]
修正した。
