### ISSUE TITLE
[enchantjs] StageSelectingで画面が更新されないことがある

### ISSUE THREAD

**Issue by eeic19** [turenar/mayfes2018-pikyou#86]
GameOverからStageSelectingに遷移したとき、矢印をクリックしても画面の表示が変化しない。
ボタン自体は機能しているようで、Stageの変更などは行うことが可能。

**Comment by aqla114** [comment]
これ、他の場所でcore.pause()を使ってるのが原因です（たぶん）

**Comment by aqla114** [comment]
#78 と同じ。

**Comment by aqla114** [comment]
解決したので閉じます。
