### ISSUE TITLE
[enchantjs] scoreの定義を明確にして、スコア機能を実装する

### ISSUE THREAD

**Issue by aqla114** [turenar/mayfes2018-pikyou#98]
現状、スコアの計算式が適当なのでこれをしっかりしたい。現時点で評価したい点は、
* コードの短さ
* if文をしっかり使えているか
* アイテムを拾ったか
です。

で、スコアはResultで表示する（つまりPlayingからの遷移時にResultに渡すようにする）ようにして、かつ、SceneManagerで管理してStageSelecting画面に表示するようにしたい。

**Comment by aqla114** [comment]
いいコードの定義
* Repeat yourself が少ない。
* 「かつ」、「または」を使えるときは使う。

スコアの定義
* 各ブロックごとにコスト定義
* チェストとったか（チェストは複数個可能）
* 行動回数

**Comment by aqla114** [comment]
ブロックのコスト
* 進む 50
* ジャンプ 50
* if 5
  * else if 3
  * else 3
* 条件 1

**Comment by aqla114** [comment]
宝箱100
最大行動回数50にしてそこから行動回数を引いたものを足す。
クリア点数100（ゲタ）

**Comment by eeic19** [comment]
ジャンプは仕様の変更により大きな減点を要さないコマンドになったので減点は10程度に変更でお願いします

**Comment by aqla114** [comment]
ジャンプの減点の変更、別issue立てるので閉じます。
